### ISSUE TITLE
packager error with example app

### ISSUE THREAD

**Issue by mmmurf** [fabriciovergal/react-native-workers#8]
loading the following URL in the browser:

http://localhost:8081/index.worker.bundle

results in the packager error printed to the terminal running the packager:

Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/mmmurf/projects/react-native-workers/example/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:71:13
    at _bundler.getResolver.getDependencyGraph.load.then (/Users/mmmurf/projects/react-native-workers/example/node_modules/react-native/packager/react-packager/src/Server/index.js:320:20)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by nbergen** [comment]
using `http://localhost:8081/index.worker.bundle?platform=android` (and presumably ios) works.

**Comment by fabriciovergara** [comment]
you should start the worker in another port, 8081 is RN default packer port that will be used by the main code.
